/**
 * What each word means, in English.
 *
 * A separate registry from `wordlist.ts` on purpose: `npm run import-words`
 * regenerates the `WORDS` array wholesale from the TSV, so a gloss written into
 * it would be silently erased the next time the list is re-imported. Keyed by
 * `id` for the same reason everything else in this pipeline is — an id is
 * stable across a re-import, where list position is not.
 *
 * ⚠ Written by an English speaker from the characters, not by Jane. These are
 * the common single-character senses a beginner meets first; several of these
 * characters carry others, and a few (才, 把) are grammatical words that no
 * short gloss really covers. Worth a native pass before anyone leans on them.
 *
 * One or two words, lower case, no articles: this sits above the pinyin in a
 * HUD the player reads in the second before they speak, not in a dictionary.
 */
export const GLOSSARY: Record<string, string> = {
  // ---- tone 1
  ma1b: "mother",
  ba1: "eight",
  san1: "three",
  qi1: "seven",
  tian1: "sky, day",
  hua1: "flower",
  shu1: "book",
  dong1: "east",
  jia1: "home",
  che1: "car",
  shuo1: "to speak",
  chi1: "to eat",
  he1: "to drink",
  shan1: "mountain",
  xin1: "heart",
  kai1: "to open",
  mao1: "cat",
  chun1: "spring",
  gao1: "tall",
  zhong1: "middle",
  duo1: "many",
  jie1: "street",
  tang1: "soup",
  bao1: "bag",
  bei1: "cup",
  fei1: "to fly",
  xing1: "star",
  xiang1: "fragrant",
  bing1: "ice",
  ting1: "to listen",

  // ---- tone 2
  ma2: "hemp",
  ba2: "to pull out",
  shi2: "ten",
  ren2: "person",
  lai2: "to come",
  tou2: "head",
  qian2: "money",
  fang2: "house",
  men2: "door",
  xue2: "to study",
  hong2: "red",
  bai2: "white",
  yu2: "fish",
  niu2: "cow",
  yang2: "sheep",
  cha2: "tea",
  tian2: "sweet",
  chang2: "long",
  nian2: "year",
  ming2: "bright",
  mang2: "busy",
  nan2: "difficult",
  wan2: "to play",
  wang2: "king",
  cai2: "only then",
  qiu2: "ball",
  tu2: "picture",
  e2: "goose",
  lan2: "blue",
  huang2: "yellow",

  // ---- tone 3
  ma3b: "horse",
  ba3: "handle",
  wu3: "five",
  jiu3: "nine",
  wo3: "I, me",
  ni3: "you",
  hao3: "good",
  mai3: "to buy",
  shui3: "water",
  gou3: "dog",
  shou3: "hand",
  kou3: "mouth",
  yan3: "eye",
  er3: "ear",
  zao3: "early",
  zou3: "to walk",
  pao3: "to run",
  xiang3: "to think",
  xiao3: "small",
  lao3: "old",
  leng3: "cold",
  duan3: "short",
  yuan3: "far",
  mi3: "rice",
  you3: "to have",
  nv3: "female",
  yu3: "rain",
  yi3: "chair",
  zhi3: "paper",
  qing3: "please",

  // ---- tone 4
  ma4b: "to scold",
  ba4: "dad",
  si4: "four",
  liu4: "six",
  er4: "two",
  da4: "big",
  shi4: "to be",
  mai4: "to sell",
  dui4: "correct",
  kan4: "to look",
  qu4: "to go",
  yao4: "to want",
  hui4: "can, will",
  kuai4: "fast",
  man4: "slow",
  re4: "hot",
  shu4: "tree",
  hua4: "speech",
  fan4: "rice, meal",
  cai4: "vegetable",
  rou4: "meat",
  mian4: "noodles",
  dian4: "electricity",
  lu4: "road",
  yue4: "moon, month",
  ke4: "lesson",
  di4: "younger brother",
  mei4: "younger sister",
  zuo4: "to sit",
  chang4: "to sing",
};
