import { describe, expect, it } from "vitest";
import { idFor, parseWord } from "./pinyin.ts";
import wordsFallback from "../data/wordsFallback.json" with { type: "json" };

// Retargeted at the published catalog snapshot (Task 13, Sep 2026): the
// word list is a Supabase `words` table now, not `wordlist.ts`'s `WORDS`
// array, and this fallback JSON is the closest thing to a flat file of it.
// Only the pinyin/id-derivation invariants survive here — they're
// properties of every row regardless of where it's stored. Live-catalog
// invariants (min_tier, no missing clip, etc.) belong to the pipeline
// scripts, not this test.
const rows = wordsFallback.rows as { id: string; hanzi: string; pinyin: string; tone: number }[];

describe("word list (wordsFallback.json rows)", () => {
  it("has unique ids", () => {
    // A duplicate id overwrites a finished recording at the same blob key —
    // silent data loss, discovered only when the clip sounds wrong in-game.
    const ids = rows.map((w) => w.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("uses ids that are safe as filenames and URLs", () => {
    for (const w of rows) {
      expect(w.id).toMatch(/^[a-z0-9]+$/);
    }
  });

  it("gives each word the tone its own pinyin says it has", () => {
    // The real mislabelling guard. `tone` decides which corridor the clip is
    // scored against, so a wrong one is a clip that teaches the wrong shape.
    // Multi-syllable words take the first toned syllable — the only one a
    // single gate could ever be built from.
    for (const w of rows) {
      const first = parseWord(w.pinyin).find((s) => s.tone !== 0);
      // If the pinyin contains no toned syllable (all neutral), treat the
      // tone as 0 to match the `tone` field in the fallback rows.
      expect(first?.tone ?? 0, `${w.hanzi} ${w.pinyin}`).toBe(w.tone);
    }
  });

  it("keeps each id derivable from its pinyin", () => {
    // Ids are generated by `npm run import-words`, never hand-written. An id
    // that no longer matches its pinyin means the two were edited apart, and
    // the recording would be filed under a name for a different word.
    for (const w of rows) {
      expect(w.id, `${w.hanzi} ${w.pinyin}`).toMatch(
        // The bare id, or the same plus a homophone suffix.
        new RegExp(`^${idFor(w.pinyin)}[a-z]*$`),
      );
    }
  });
});
