import { describe, expect, it } from "vitest";
import { GLOSSARY } from "./glossary.ts";
import { idFor, parseWord } from "./pinyin.ts";
import { WORDS } from "./wordlist.ts";

describe("word list", () => {
  it("has unique ids", () => {
    // A duplicate id overwrites a finished recording at the same blob key —
    // silent data loss, discovered only when the clip sounds wrong in-game.
    const ids = WORDS.map((w) => w.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("uses ids that are safe as filenames and URLs", () => {
    for (const w of WORDS) {
      expect(w.id).toMatch(/^[a-z0-9]+$/);
    }
  });

  it("gives every word a tone, hanzi and pinyin", () => {
    for (const w of WORDS) {
      expect([1, 2, 3, 4]).toContain(w.tone);
      expect(w.hanzi.length).toBeGreaterThan(0);
      expect(w.pinyin.length).toBeGreaterThan(0);
    }
  });

  it("gives each word the tone its own pinyin says it has", () => {
    // The real mislabelling guard. `tone` decides which corridor the clip is
    // scored against, so a wrong one is a clip that teaches the wrong shape.
    // Multi-syllable words take the first toned syllable — the only one a
    // single gate could ever be built from.
    for (const w of WORDS) {
      const first = parseWord(w.pinyin).find((s) => s.tone !== 0);
      expect(first?.tone, `${w.hanzi} ${w.pinyin}`).toBe(w.tone);
    }
  });

  it("keeps each id derivable from its pinyin", () => {
    // Ids are generated by `npm run import-words`, never hand-written. An id
    // that no longer matches its pinyin means the two were edited apart, and
    // the recording would be filed under a name for a different word.
    for (const w of WORDS) {
      expect(w.id, `${w.hanzi} ${w.pinyin}`).toMatch(
        // The bare id, or the same plus a homophone suffix.
        new RegExp(`^${idFor(w.pinyin)}[a-z]*$`),
      );
    }
  });
});

describe("the glossary", () => {
  it("gives every word an English gloss", () => {
    const missing = WORDS.filter((w) => !GLOSSARY[w.id]).map((w) => `${w.hanzi} (${w.id})`);
    expect(missing).toEqual([]);
  });

  it("glosses nothing that is not in the word list", () => {
    // A stale key is a translation that will never be shown, and usually the
    // trace of an id that moved.
    const ids = new Set(WORDS.map((w) => w.id));
    expect(Object.keys(GLOSSARY).filter((id) => !ids.has(id))).toEqual([]);
  });

  it("keeps a gloss short enough for one HUD line", () => {
    // It sits above the pinyin on a 420px canvas. A definition wraps and
    // pushes the syllable off its line.
    for (const [id, gloss] of Object.entries(GLOSSARY)) {
      expect(gloss.length, id).toBeLessThanOrEqual(18);
      expect(gloss, id).toBe(gloss.trim());
      // Lower case, so the line reads as a gloss rather than a heading. "I" is
      // the one word English will not let us lower-case.
      expect(gloss.replace("I", "i"), id).toBe(gloss.replace("I", "i").toLowerCase());
    }
  });
});
