import { useEffect, useMemo, useRef, useState } from "react";
import { REST_CHAO } from "../game/dynamics.ts";
import type { Contour } from "../game/contours.ts";
import { corridorChaoAt, type GateShape, type Tone } from "../game/gates.ts";
import { birdXFrac } from "../game/run.ts";
import type { Word } from "../game/words.ts";
import type { Polyline } from "../game/tuning.ts";
import { rgba } from "../render/palette.ts";
import { chaoToY } from "../render/scene.ts";
import { drawVisualiser } from "../render/visualiser.ts";
import { SPAN_MS } from "../ui/Visualiser.tsx";
import tonePairData from "./tonePairPolylines.json";
import { textbookTonePairPolyline } from "./tonePairTheory.ts";

/**
 * The cropped audio for each fixture — the exact span its contour was
 * measured over (see `generate-tonepair-polylines.ts`), so `<audio>`'s own
 * `currentTime / duration` maps directly onto a word's `points` t axis with
 * no separate offset to track. Globbed rather than imported by name because
 * the file list is generator output, not something to hand-maintain here;
 * `eager` keeps this a plain synchronous map like the JSON import above it.
 */
const AUDIO_URLS = import.meta.glob("../../fixtures/tonepairs/wav/*-cropped.wav", {
  eager: true,
  query: "?url",
  import: "default",
}) as Record<string, string>;

function audioUrlFor(id: string): string | null {
  const entry = Object.entries(AUDIO_URLS).find(([path]) => path.endsWith(`/${id}-cropped.wav`));
  return entry?.[1] ?? null;
}

/**
 * Exploration-only Lab tab (tone-pair-testing branch): draws the raw measured
 * chao contour for each `fixtures/tonepairs/*.m4a` recording, generated by
 * `npm run tonepairs:generate` (`src/dev/generate-tonepair-polylines.ts`).
 *
 * Not wired into any gameplay path. The point is only to see what a tone
 * pair's pitch contour actually looks like before deciding how it should be
 * templated into a `GateShape`/polyline — see docs/tonepairs/. Points are the
 * whole-word span (both syllables + the pause between them, not a single
 * `longestVoicedRun`), which the single-syllable `clipCut.ts` pipeline
 * deliberately does not produce.
 */

const CARD_W = 420;
const CARD_H = 260;

interface TonePairWord {
  id: string;
  hanzi: string;
  pinyin: string;
  tones: number[];
  f0Center: number;
  durationMs: number;
  points: Array<number | null>;
}

const WORDS = tonePairData.words as TonePairWord[];

const LINE_COLOR = "rgba(150, 60, 130,";
const DOT_COLOR = "rgba(210, 40, 40,";
const TEXTBOOK_COLOR = "rgba(50, 90, 190,";
const TEXTBOOK_STEPS = 48;

/** The two tones a fixture's `tones` field carries, or null if it's not a pair. */
function tonePairOf(tones: number[]): [Tone, Tone] | null {
  return tones.length >= 2 ? [tones[0] as Tone, tones[1] as Tone] : null;
}

/** Linear interpolation over `points`, which are evenly spaced across t in [0,1]. */
function chaoAtT(points: Array<number | null>, t: number): number | null {
  const clamped = Math.min(1, Math.max(0, t));
  const pos = clamped * (points.length - 1);
  const i0 = Math.floor(pos);
  const i1 = Math.min(points.length - 1, i0 + 1);
  const a = points[i0];
  const b = points[i1];
  if (a === null || b === null) return a ?? b;
  const frac = pos - i0;
  return a + (b - a) * frac;
}

function drawChart(
  canvas: HTMLCanvasElement,
  word: TonePairWord,
  playheadT: number | null,
  showTextbook: boolean,
): void {
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  const dpr = window.devicePixelRatio || 1;
  canvas.width = CARD_W * dpr;
  canvas.height = CARD_H * dpr;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, CARD_W, CARD_H);

  // Chao grid, same mapping the game itself uses.
  ctx.strokeStyle = rgba("grid", 0.35);
  ctx.lineWidth = 1;
  ctx.font = "11px sans-serif";
  ctx.fillStyle = rgba("grid", 0.6);
  for (let chao = 1; chao <= 5; chao++) {
    const y = chaoToY(chao, CARD_H);
    ctx.beginPath();
    ctx.moveTo(0, y);
    ctx.lineTo(CARD_W, y);
    ctx.stroke();
    ctx.fillText(String(chao), 4, y - 3);
  }

  // Co-articulation midpoint marker, per the reference doc's ~t=0.5 seam
  // between the two syllables — purely a visual guide, not measured.
  ctx.strokeStyle = rgba("grid", 0.5);
  ctx.setLineDash([4, 4]);
  ctx.beginPath();
  ctx.moveTo(CARD_W / 2, 0);
  ctx.lineTo(CARD_W / 2, CARD_H);
  ctx.stroke();
  ctx.setLineDash([]);

  // The measured contour. Breaks the line across any gap resampleContour
  // couldn't fill (null) — an honest gap in the signal, not interpolated.
  ctx.strokeStyle = `${LINE_COLOR} 0.9)`;
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  let drawing = false;
  word.points.forEach((chao, i) => {
    const x = (i / (word.points.length - 1)) * CARD_W;
    if (chao === null) {
      drawing = false;
      return;
    }
    const y = chaoToY(chao, CARD_H);
    if (!drawing) {
      ctx.moveTo(x, y);
      drawing = true;
    } else {
      ctx.lineTo(x, y);
    }
  });
  ctx.stroke();

  // The textbook reference: §2/§3 citation Chao values run through the same
  // sandhi rules, over the whole card's t axis — not the measured recording,
  // a prediction of what the recording "should" look like per the theory.
  if (showTextbook) {
    const pair = tonePairOf(word.tones);
    if (pair) {
      const shape: GateShape = { polyline: textbookTonePairPolyline(...pair), durationS: 1 };
      ctx.strokeStyle = `${TEXTBOOK_COLOR} 0.85)`;
      ctx.lineWidth = 2;
      ctx.setLineDash([2, 5]);
      ctx.beginPath();
      for (let i = 0; i <= TEXTBOOK_STEPS; i++) {
        const t = i / TEXTBOOK_STEPS;
        const x = t * CARD_W;
        const y = chaoToY(corridorChaoAt(shape, t), CARD_H);
        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();
      ctx.setLineDash([]);
    }
  }

  // The playhead — where the audio currently is, on the same t/chao axes as
  // the line above. This is the whole point of syncing audio to the chart:
  // seeing exactly which frame of the recording maps to a given point on the
  // measured shape, e.g. where the tone actually changes.
  if (playheadT !== null) {
    const chao = chaoAtT(word.points, playheadT);
    if (chao !== null) {
      const x = playheadT * CARD_W;
      const y = chaoToY(chao, CARD_H);
      ctx.strokeStyle = rgba("grid", 0.6);
      ctx.beginPath();
      ctx.moveTo(x, 0);
      ctx.lineTo(x, CARD_H);
      ctx.stroke();
      ctx.fillStyle = `${DOT_COLOR} 1)`;
      ctx.beginPath();
      ctx.arc(x, y, 5, 0, Math.PI * 2);
      ctx.fill();
    }
  }
}

function TonePairCard({ word, showTextbook }: { word: TonePairWord; showTextbook: boolean }) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const rafRef = useRef<number | null>(null);
  const [playing, setPlaying] = useState(false);
  const audioUrl = audioUrlFor(word.id);

  // Static draw whenever the word, or the textbook toggle, changes.
  useEffect(() => {
    if (canvasRef.current) drawChart(canvasRef.current, word, null, showTextbook);
  }, [word, showTextbook]);

  useEffect(() => {
    if (!playing) return;
    const tick = () => {
      const audio = audioRef.current;
      const canvas = canvasRef.current;
      if (audio && canvas && audio.duration > 0) {
        drawChart(canvas, word, audio.currentTime / audio.duration, showTextbook);
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    };
  }, [playing, word, showTextbook]);

  return (
    <div className="word-card tone-average-card">
      <canvas ref={canvasRef} />
      <span className="param-name">
        {word.hanzi} {word.pinyin} — citation [{word.tones.join("-")}] — f0Center{" "}
        {word.f0Center}Hz — {Math.round(word.durationMs)}ms
      </span>
      {audioUrl ? (
        <audio
          ref={audioRef}
          src={audioUrl}
          controls
          onPlay={() => setPlaying(true)}
          onPause={() => setPlaying(false)}
          onEnded={() => {
            setPlaying(false);
            if (canvasRef.current) drawChart(canvasRef.current, word, null, showTextbook);
          }}
          style={{ width: "100%", marginTop: 6 }}
        />
      ) : (
        <p className="param-help">no cropped audio found for "{word.id}"</p>
      )}
    </div>
  );
}

/**
 * A tone-pair fixture's `points` (evenly spaced, possibly-null samples) as a
 * `Polyline` (sparse `[t, chao]` pairs) — the shape `shapeForWord`/
 * `corridorChaoAt` actually consume. Nulls (a gap `resampleContour` couldn't
 * fill) are dropped rather than interpolated, same honesty rule the grid
 * view's own line-break already follows.
 */
function toPolyline(points: Array<number | null>): Polyline {
  const line: Polyline = [];
  points.forEach((chao, i) => {
    if (chao !== null) line.push([i / (points.length - 1), chao]);
  });
  return line;
}

/**
 * A minimal but fully-shaped `Word`, standing in for a catalog row so
 * `drawVisualiser` (built for the real game's `Word` type) can draw a
 * tone-pair fixture on the exact same axes and scale as the shipped
 * visualiser — same grid, same target-ghost styling, same dot. Every field
 * `drawVisualiser`/`shapeForWord` doesn't read is a harmless placeholder.
 */
function fixtureAsWord(word: TonePairWord): Word {
  return {
    id: word.id,
    hanzi: word.hanzi,
    pinyin: word.pinyin,
    speakerId: "jane",
    english: "",
    tone: (word.tones[0] ?? 1) as Tone,
    tones: word.tones as Tone[],
    syllables: word.tones.length,
    clipKey: "",
    durationS: word.durationMs / 1000,
    onsetS: 0,
    clipS: word.durationMs / 1000,
    polyline: toPolyline(word.points),
    minTier: "free",
    listIds: [],
    updatedAt: "",
  };
}

const VIS_W = 360;
const VIS_H = 640;

/** Right margin, matching `render/visualiser.ts`'s own private `END_PAD_FRAC`. */
const VIS_END_PAD_FRAC = 0.04;

/**
 * Reproduces `render/visualiser.ts`'s private `xFor` exactly (t=0 sits at
 * `birdXFrac()`, same as the game's bird) so the textbook overlay lands on
 * the identical x axis `drawVisualiser` itself draws the measured target
 * and dot on — not exported, so duplicated here rather than reached into.
 */
function visXFor(tMs: number, spanMs: number, width: number): number {
  const startFrac = birdXFrac();
  const usable = width * (1 - VIS_END_PAD_FRAC - startFrac);
  return width * startFrac + (Math.min(tMs, spanMs) / spanMs) * usable;
}

/**
 * The same panel the shipped tone visualiser draws (`drawVisualiser`,
 * `src/render/visualiser.ts`) — identical grid, identical target-ghost
 * styling, identical dot — fed a tone-pair fixture standing in for a real
 * `Word`. The point is a like-for-like comparison against the product,
 * rather than the grid view's own bespoke chart above.
 */
function TonePairVisualiserView({
  word,
  showTextbook,
}: {
  word: TonePairWord;
  showTextbook: boolean;
}) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const audioRef = useRef<HTMLAudioElement>(null);
  const rafRef = useRef<number | null>(null);
  const trailRef = useRef<Contour>({ points: [], startedAtMs: 0, endedAtMs: null });
  const [playing, setPlaying] = useState(false);
  const audioUrl = audioUrlFor(word.id);
  const fakeWord = useMemo(() => fixtureAsWord(word), [word]);
  const pair = useMemo(() => tonePairOf(word.tones), [word]);

  const draw = (live: Contour | null, chao: number, voiced: boolean) => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;
    const dpr = window.devicePixelRatio || 1;
    canvas.width = VIS_W * dpr;
    canvas.height = VIS_H * dpr;
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    drawVisualiser(ctx, VIS_W, VIS_H, {
      tone: fakeWord.tone,
      word: fakeWord,
      live,
      finished: [],
      spanMs: SPAN_MS,
      chao,
      voiced,
    });

    // Textbook reference, on drawVisualiser's own x axis (birdXFrac-offset,
    // real milliseconds) — drawn over the whole fixture duration, same as
    // drawVisualiser's own measured-target ghost stops at its own length
    // rather than holding out to `spanMs`.
    if (showTextbook && pair) {
      const shape: GateShape = { polyline: textbookTonePairPolyline(...pair), durationS: 1 };
      const durationMs = word.durationMs;
      ctx.save();
      ctx.setLineDash([2, 6]);
      ctx.strokeStyle = `${TEXTBOOK_COLOR} 0.8)`;
      ctx.lineWidth = 2;
      ctx.beginPath();
      for (let i = 0; i <= TEXTBOOK_STEPS; i++) {
        const t = i / TEXTBOOK_STEPS;
        const x = visXFor(t * durationMs, SPAN_MS, VIS_W);
        const y = chaoToY(corridorChaoAt(shape, t), VIS_H);
        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();
      ctx.restore();
    }
  };

  // Idle draw: target ghost only, dot at rest, whenever the fixture or the
  // textbook toggle changes.
  useEffect(() => {
    trailRef.current = { points: [], startedAtMs: 0, endedAtMs: null };
    draw(null, REST_CHAO, false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [word, showTextbook]);

  useEffect(() => {
    if (!playing) return;
    const tick = () => {
      const audio = audioRef.current;
      if (audio && audio.duration > 0) {
        const t = audio.currentTime / audio.duration;
        const chao = chaoAtT(word.points, t);
        const tMs = audio.currentTime * 1000;
        if (chao !== null) {
          trailRef.current.points.push({ tMs, chao });
          draw(trailRef.current, chao, true);
        } else {
          draw(trailRef.current, REST_CHAO, false);
        }
      }
      rafRef.current = requestAnimationFrame(tick);
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => {
      if (rafRef.current !== null) cancelAnimationFrame(rafRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playing, word, showTextbook]);

  return (
    <div className="word-card tone-average-card">
      <canvas ref={canvasRef} style={{ width: VIS_W, height: VIS_H }} />
      {audioUrl ? (
        <audio
          ref={audioRef}
          src={audioUrl}
          controls
          onPlay={() => {
            trailRef.current = { points: [], startedAtMs: 0, endedAtMs: null };
            setPlaying(true);
          }}
          onPause={() => setPlaying(false)}
          onEnded={() => {
            setPlaying(false);
            draw(null, REST_CHAO, false);
          }}
          style={{ width: VIS_W, marginTop: 6 }}
        />
      ) : (
        <p className="param-help">no cropped audio found for "{word.id}"</p>
      )}
    </div>
  );
}

export function TonePairs() {
  const [selectedId, setSelectedId] = useState(WORDS[0]?.id ?? "");
  const [showTextbook, setShowTextbook] = useState(false);
  const selected = WORDS.find((w) => w.id === selectedId) ?? WORDS[0] ?? null;

  return (
    <div className="word-gates">
      <p className="param-help">
        Raw measured contours from `fixtures/tonepairs/` — the whole word span
        (both syllables, plus the pause between them), not a single{" "}
        <code>longestVoicedRun</code>. Measured the same way every shipped
        single-syllable clip is: f0Center seeded at Jane's pinned 168 and
        recentred per-take (`measurePitchReference`), range measured at ±15
        semitones (`MEASURE_RANGE_SEMITONES`), not the tracker's narrower
        gameplay default — so these are directly comparable to the shipped
        corridors. Regenerate with <code>npm run tonepairs:generate</code>{" "}
        after adding a recording.
        Dashed line marks the rough syllable-1/syllable-2 seam (~t=0.5), not a
        measured boundary. "Citation" tones are read off the pinyin, not
        sandhi-adjusted — compare the shape to what the sandhi rule predicts.
        All four fixtures happen to be citation [3,2]: half-3rd sandhi (dip,
        no rise back to 4) into a rising T2.
      </p>

      <label className="param-name" style={{ display: "flex", alignItems: "center", gap: 8 }}>
        <input
          type="checkbox"
          checked={showTextbook}
          onChange={(e) => setShowTextbook(e.target.checked)}
        />
        show textbook reference (docs/tonepairs — citation Chao values run
        through the §3 sandhi rules, not measured)
      </label>

      <div className="word-grid tone-average-grid">
        {WORDS.map((w) => (
          <TonePairCard key={w.id} word={w} showTextbook={showTextbook} />
        ))}
      </div>

      <p className="param-help" style={{ marginTop: 24 }}>
        Same fixture, drawn through the shipped visualiser's own renderer
        (<code>drawVisualiser</code>) — identical grid, target-ghost styling
        and dot, at the game's own {VIS_W}×{VIS_H} canvas and {SPAN_MS}ms
        span, for a direct comparison against the real product.
      </p>
      <select
        className="param-name"
        value={selectedId}
        onChange={(e) => setSelectedId(e.target.value)}
        style={{ marginBottom: 12 }}
      >
        {WORDS.map((w) => (
          <option key={w.id} value={w.id}>
            {w.hanzi} {w.pinyin} [{w.tones.join("-")}]
          </option>
        ))}
      </select>
      {selected && <TonePairVisualiserView word={selected} showTextbook={showTextbook} />}
    </div>
  );
}
