/**
 * Generated by the Supabase MCP `generate_typescript_types` against the
 * flappytone project, and committed so the client is type-checked against the
 * real schema rather than a hand-written guess.
 *
 * Do not edit by hand. Regenerate after every migration.
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      daily_runs: {
        Row: {
          count: number
          day: string
          updated_at: string
          user_id: string
        }
        Insert: {
          count?: number
          day: string
          updated_at?: string
          user_id: string
        }
        Update: {
          count?: number
          day?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_runs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      entitlements: {
        Row: {
          has_access: boolean
          source: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          has_access?: boolean
          source?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          has_access?: boolean
          source?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "entitlements_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      leaderboard_scores: {
        Row: {
          best_score: number
          updated_at: string
          user_id: string
          week_id: string
        }
        Insert: {
          best_score: number
          updated_at?: string
          user_id: string
          week_id: string
        }
        Update: {
          best_score?: number
          updated_at?: string
          user_id?: string
          week_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leaderboard_scores_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lists: {
        Row: {
          id: string
          meta: Json
          min_tier: string
          name: string
          source: string | null
        }
        Insert: {
          id: string
          meta?: Json
          min_tier?: string
          name: string
          source?: string | null
        }
        Update: {
          id?: string
          meta?: Json
          min_tier?: string
          name?: string
          source?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          best_score: number
          created_at: string
          display_name: string
          id: string
          is_public: boolean
          marketing_consent: boolean
          marketing_consent_at: string | null
          streak_best: number
          streak_current: number
          synced_at: string | null
          total_gates: number
          total_runs: number
        }
        Insert: {
          best_score?: number
          created_at?: string
          display_name: string
          id: string
          is_public?: boolean
          marketing_consent?: boolean
          marketing_consent_at?: string | null
          streak_best?: number
          streak_current?: number
          synced_at?: string | null
          total_gates?: number
          total_runs?: number
        }
        Update: {
          best_score?: number
          created_at?: string
          display_name?: string
          id?: string
          is_public?: boolean
          marketing_consent?: boolean
          marketing_consent_at?: string | null
          streak_best?: number
          streak_current?: number
          synced_at?: string | null
          total_gates?: number
          total_runs?: number
        }
        Relationships: []
      }
      speakers: {
        Row: {
          accent: string
          active: boolean
          created_at: string
          f0_seed: number
          gender: string
          id: string
          is_default: boolean
          name: string
        }
        Insert: {
          accent?: string
          active?: boolean
          created_at?: string
          f0_seed: number
          gender: string
          id: string
          is_default?: boolean
          name: string
        }
        Update: {
          accent?: string
          active?: boolean
          created_at?: string
          f0_seed?: number
          gender?: string
          id?: string
          is_default?: boolean
          name?: string
        }
        Relationships: []
      }
      tone_stats: {
        Row: {
          attempts: number
          best_accuracy: number
          sum_accuracy: number
          tone: number
          unheard: number
          updated_at: string
          user_id: string
        }
        Insert: {
          attempts?: number
          best_accuracy?: number
          sum_accuracy?: number
          tone: number
          unheard?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          attempts?: number
          best_accuracy?: number
          sum_accuracy?: number
          tone?: number
          unheard?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tone_stats_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      word_clips: {
        Row: {
          clip_key: string | null
          clip_s: number | null
          contour: Json | null
          created_at: string
          duration_s: number | null
          onset_s: number | null
          polyline: Json | null
          raw_key: string | null
          recorded_at: string | null
          recorded_session: string | null
          speaker_id: string
          status: string
          updated_at: string
          word_id: string
        }
        Insert: {
          clip_key?: string | null
          clip_s?: number | null
          contour?: Json | null
          created_at?: string
          duration_s?: number | null
          onset_s?: number | null
          polyline?: Json | null
          raw_key?: string | null
          recorded_at?: string | null
          recorded_session?: string | null
          speaker_id: string
          status?: string
          updated_at?: string
          word_id: string
        }
        Update: {
          clip_key?: string | null
          clip_s?: number | null
          contour?: Json | null
          created_at?: string
          duration_s?: number | null
          onset_s?: number | null
          polyline?: Json | null
          raw_key?: string | null
          recorded_at?: string | null
          recorded_session?: string | null
          speaker_id?: string
          status?: string
          updated_at?: string
          word_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "word_clips_speaker_id_fkey"
            columns: ["speaker_id"]
            isOneToOne: false
            referencedRelation: "speakers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "word_clips_word_id_fkey"
            columns: ["word_id"]
            isOneToOne: false
            referencedRelation: "words"
            referencedColumns: ["id"]
          },
        ]
      }
      word_lists: {
        Row: {
          list_id: string
          word_id: string
        }
        Insert: {
          list_id: string
          word_id: string
        }
        Update: {
          list_id?: string
          word_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "word_lists_list_id_fkey"
            columns: ["list_id"]
            isOneToOne: false
            referencedRelation: "lists"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "word_lists_word_id_fkey"
            columns: ["word_id"]
            isOneToOne: false
            referencedRelation: "words"
            referencedColumns: ["id"]
          },
        ]
      }
      words: {
        Row: {
          clip_key: string | null
          clip_s: number | null
          contour: Json | null
          created_at: string
          duration_s: number | null
          english: string
          hanzi: string
          id: string
          meta: Json
          min_tier: string
          onset_s: number | null
          pinyin: string
          polyline: Json | null
          position: number
          raw_key: string | null
          recorded_at: string | null
          recorded_session: string | null
          status: string
          syllables: number
          tone: number
          tones: number[]
          updated_at: string
        }
        Insert: {
          clip_key?: string | null
          clip_s?: number | null
          contour?: Json | null
          created_at?: string
          duration_s?: number | null
          english?: string
          hanzi: string
          id: string
          meta?: Json
          min_tier?: string
          onset_s?: number | null
          pinyin: string
          polyline?: Json | null
          position: number
          raw_key?: string | null
          recorded_at?: string | null
          recorded_session?: string | null
          status?: string
          syllables?: number
          tone: number
          tones?: number[]
          updated_at?: string
        }
        Update: {
          clip_key?: string | null
          clip_s?: number | null
          contour?: Json | null
          created_at?: string
          duration_s?: number | null
          english?: string
          hanzi?: string
          id?: string
          meta?: Json
          min_tier?: string
          onset_s?: number | null
          pinyin?: string
          polyline?: Json | null
          position?: number
          raw_key?: string | null
          recorded_at?: string | null
          recorded_session?: string | null
          status?: string
          syllables?: number
          tone?: number
          tones?: number[]
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      board: { Args: { p_limit?: number; p_week: string }; Returns: Json }
      board_period: {
        Args: { p_limit?: number; p_period: string }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
